/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author pc
 */
public class Home extends javax.swing.JFrame {
 JPanel pn;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_qlpong = new javax.swing.JButton();
        btn_qlkh = new javax.swing.JButton();
        btn_qlnv = new javax.swing.JButton();
        btn_qldv = new javax.swing.JButton();
        btn_qllaixe = new javax.swing.JButton();
        btn_thanhtoan = new javax.swing.JButton();
        btn_timkiemkh = new javax.swing.JButton();
        btn_tknv = new javax.swing.JButton();
        btn_tkphong = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbanh = new javax.swing.JLabel();
        panelBD = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btn_qlpong.setBackground(new java.awt.Color(51, 51, 51));
        btn_qlpong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_qlpong.setForeground(new java.awt.Color(255, 255, 255));
        btn_qlpong.setText("     Quản Lý Phòng");
        btn_qlpong.setFocusPainted(false);
        btn_qlpong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_qlpong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlpongActionPerformed(evt);
            }
        });

        btn_qlkh.setBackground(new java.awt.Color(51, 51, 51));
        btn_qlkh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_qlkh.setForeground(new java.awt.Color(255, 255, 255));
        btn_qlkh.setText("     Quản Lý Khách Hàng");
        btn_qlkh.setFocusPainted(false);
        btn_qlkh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_qlkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlkhActionPerformed(evt);
            }
        });

        btn_qlnv.setBackground(new java.awt.Color(51, 51, 51));
        btn_qlnv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_qlnv.setForeground(new java.awt.Color(255, 255, 255));
        btn_qlnv.setText("     Quản Lý Nhân Viên");
        btn_qlnv.setFocusPainted(false);
        btn_qlnv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_qlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnvActionPerformed(evt);
            }
        });

        btn_qldv.setBackground(new java.awt.Color(51, 51, 51));
        btn_qldv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_qldv.setForeground(new java.awt.Color(255, 255, 255));
        btn_qldv.setText("     Quản Lý Dịch Vụ");
        btn_qldv.setFocusPainted(false);
        btn_qldv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_qldv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qldvActionPerformed(evt);
            }
        });

        btn_qllaixe.setBackground(new java.awt.Color(51, 51, 51));
        btn_qllaixe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_qllaixe.setForeground(new java.awt.Color(255, 255, 255));
        btn_qllaixe.setText("     Quản Lý Lái Xe");
        btn_qllaixe.setFocusPainted(false);
        btn_qllaixe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_qllaixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qllaixeActionPerformed(evt);
            }
        });

        btn_thanhtoan.setBackground(new java.awt.Color(51, 51, 51));
        btn_thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_thanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btn_thanhtoan.setText("     Thanh Toán");
        btn_thanhtoan.setFocusPainted(false);
        btn_thanhtoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhtoanActionPerformed(evt);
            }
        });

        btn_timkiemkh.setBackground(new java.awt.Color(51, 51, 51));
        btn_timkiemkh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timkiemkh.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiemkh.setText("     Tìm Kiếm Khách Hàng");
        btn_timkiemkh.setFocusPainted(false);
        btn_timkiemkh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_timkiemkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemkhActionPerformed(evt);
            }
        });

        btn_tknv.setBackground(new java.awt.Color(51, 51, 51));
        btn_tknv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tknv.setForeground(new java.awt.Color(255, 255, 255));
        btn_tknv.setText("     Tìm Kiếm Nhân Viên");
        btn_tknv.setFocusPainted(false);
        btn_tknv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_tknv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tknvActionPerformed(evt);
            }
        });

        btn_tkphong.setBackground(new java.awt.Color(51, 51, 51));
        btn_tkphong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tkphong.setForeground(new java.awt.Color(255, 255, 255));
        btn_tkphong.setText("     Tìm Kiếm Phòng");
        btn_tkphong.setFocusPainted(false);
        btn_tkphong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_tkphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tkphongActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(51, 51, 51));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("     Đăng Xuất");
        btn_logout.setFocusPainted(false);
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMINISTRATOR");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/ad.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_qlpong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_qlkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_qlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_qldv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_qllaixe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_timkiemkh, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(btn_tknv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_tkphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_qlpong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_qlkh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_qlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_qldv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_qllaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_timkiemkh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tknv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tkphong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        lbanh.setText("jLabel1");

        panelBD.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(panelBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(lbanh, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(800, 800, 800)
                        .addComponent(panelBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbanh, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_qlpongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlpongActionPerformed
        // TODO add your handling code here:
        QLPhong jf = new QLPhong();
        jf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_qlpongActionPerformed

    private void btn_qlkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlkhActionPerformed
        // TODO add your handling code here:
    
         panelBD.setBounds(280, 140, 1196, 639);
         panelBD.removeAll();
        
          pn = new PanelQLLaiXe();
          panelBD.add(pn);
        panelBD.validate();
       
    }//GEN-LAST:event_btn_qlkhActionPerformed

    private void btn_qlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnvActionPerformed
        // TODO add your handling code here:
        QLNhanVien jf = new QLNhanVien();
        jf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_qlnvActionPerformed

    private void btn_qldvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qldvActionPerformed
        // TODO add your handling code here:
        QLDichVu jf = new QLDichVu();
        jf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_qldvActionPerformed

    private void btn_qllaixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qllaixeActionPerformed
        // TODO add your handling code here:
        new QLLaiXe().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_qllaixeActionPerformed

    private void btn_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhtoanActionPerformed
        // TODO add your handling code here:
        CheckOut1 jf = new CheckOut1();
        jf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_thanhtoanActionPerformed

    private void btn_timkiemkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemkhActionPerformed
        // TODO add your handling code here:
        ThongTinKhachHang jf = new ThongTinKhachHang();
        jf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_timkiemkhActionPerformed

    private void btn_tknvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tknvActionPerformed
        // TODO add your handling code here:
        ThongTInNhanVIen jf = new ThongTInNhanVIen();
        jf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_tknvActionPerformed

    private void btn_tkphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tkphongActionPerformed
        // TODO add your handling code here:
        ThongTinPhong jf = new ThongTinPhong();
        jf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_tkphongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("hotel/management/system/icons/home.png"));
        Image i3 = i1.getImage().getScaledInstance(1320, 900, Image.SCALE_DEFAULT);
        ImageIcon i2 = new ImageIcon(i3);
        lbanh.setIcon(i2);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_qldv;
    private javax.swing.JButton btn_qlkh;
    private javax.swing.JButton btn_qllaixe;
    private javax.swing.JButton btn_qlnv;
    private javax.swing.JButton btn_qlpong;
    private javax.swing.JButton btn_thanhtoan;
    private javax.swing.JButton btn_timkiemkh;
    private javax.swing.JButton btn_tknv;
    private javax.swing.JButton btn_tkphong;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbanh;
    private javax.swing.JPanel panelBD;
    // End of variables declaration//GEN-END:variables
}
