/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hotel.management.system;

import Process.ChucNang;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kdt09
 */
public class PanelCheckOut extends javax.swing.JPanel {

    /**
     * Creates new form PanelCheckOut
     */
    public PanelCheckOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGioiTinh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaPhong7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNgayDen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNgayDi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnTinhTien = new javax.swing.JButton();
        txtDVTinh = new javax.swing.JTextField();
        txtMaPhieu = new javax.swing.JTextField();
        oo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_thoat = new javax.swing.JButton();
        txtCCCD = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsongayo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 251, 203, -1));

        jLabel15.setText("Số ngày ở");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 254, 74, -1));

        jLabel6.setText("Giới tính");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 254, 74, -1));
        add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 183, 203, -1));

        jLabel7.setText("SĐT");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 186, 74, -1));
        add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 155, 203, -1));

        jLabel8.setText("Địa chỉ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 158, 74, -1));
        add(txtMaPhong7, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 217, 203, -1));

        jLabel9.setText("Mã Phòng");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 220, 74, -1));
        add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 251, 203, -1));

        jLabel10.setText("Đơn giá");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 254, 74, -1));
        add(txtNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 183, 203, -1));

        jLabel11.setText("Ngày Đến");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 186, 74, -1));
        add(txtNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 217, 203, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã Phòng");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 98, 90, -1));

        jLabel12.setText("Ngày Đi");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 220, 74, -1));

        txtMaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txtMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 91, 203, -1));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 91, 90, 31));

        btnTinhTien.setBackground(new java.awt.Color(0, 255, 51));
        btnTinhTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTinhTien.setForeground(new java.awt.Color(255, 255, 255));
        btnTinhTien.setText("Tính Tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });
        add(btnTinhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 102, 32));
        add(txtDVTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 155, 203, -1));
        add(txtMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 155, 203, -1));

        oo.setText("Đơn vị tính");
        add(oo, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 158, 74, -1));

        jLabel3.setText("Mã Phiếu Thuê");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 158, 89, -1));

        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 331, 102, 32));
        add(txtCCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 183, 203, -1));
        add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 340, 203, 32));

        jLabel4.setText("CCCD");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 186, 74, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Thành tiền");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 341, 122, -1));
        add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 217, 203, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("    THANH TOÁN");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 0, 1004, -1));

        jLabel5.setText("Họ Tên");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 74, -1));
        add(txtsongayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 251, 203, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        ResultSet res = ChucNang.getTTKH(txtMaPhong.getText());
        try {
            if(res.next()){
                   while (res.next()) {
                txtMaPhieu.setText(res.getString(7));
                txtCCCD.setText(res.getString(2));
                txtHoten.setText(res.getString(3));
                txtGioiTinh.setText(res.getString(4));
                txtDiaChi.setText(res.getString(5));
                txtSDT.setText(res.getString(6));
                txtMaPhong7.setText(txtMaPhong.getText());
                txtDonGia.setText(res.getString(11));
                txtDVTinh.setText(res.getString(12));
                txtNgayDen.setText(res.getString(8));
                if (res.getString(9) != null) {
                    txtNgayDi.setText(res.getString(9));

                    LocalDate ngayDen = LocalDate.parse(txtNgayDen.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                    LocalDate ngayDi = LocalDate.parse(txtNgayDi.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                    long soNgayO = Math.abs(ChronoUnit.DAYS.between(ngayDen, ngayDi));

                    txtsongayo.setText(Long.toString(soNgayO));

                    txtTongTien.setText(res.getString(10));
                } else {
                    txtNgayDi.setText(LocalDate.now().toString());
                    LocalDate ngayDen = LocalDate.parse(txtNgayDen.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                    LocalDate ngayDi = LocalDate.parse(txtNgayDi.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                    long soNgayO = Math.abs(ChronoUnit.DAYS.between(ngayDen, ngayDi));

                    if (soNgayO == 0) {
                        soNgayO++;
                    }

                    txtsongayo.setText(Long.toString(soNgayO));
                    txtTongTien.setText(res.getString(10));
                }
            }
                 
            }
           else{
                  JOptionPane.showMessageDialog(null, "Phòng này chưa được thuê");
                           }

        } catch (SQLException ex) {
            Logger.getLogger(CheckOut1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        // TODO add your handling code here:

        if (txtTongTien.getText().equalsIgnoreCase("")) {
            LocalDate ngayDen = LocalDate.parse(txtNgayDen.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            LocalDate ngayDi = LocalDate.parse(txtNgayDi.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            long soNgayO = Math.abs(ChronoUnit.DAYS.between(ngayDen, ngayDi));

            if (soNgayO == 0) {
                soNgayO++;
            }

            long tongTien = soNgayO * Integer.parseInt(txtDonGia.getText());
            ChucNang.suaPhieuThue(txtNgayDi.getText(), tongTien, txtMaPhieu.getText(), txtMaPhong.getText());
            txtNgayDi.setText(ngayDi.toString());
            txtsongayo.setText(String.valueOf(soNgayO));
            txtTongTien.setText(tongTien + "");
        } else {
            JOptionPane.showMessageDialog(null, "Đã tính tiền!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_thoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel oo;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDVTinh;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaPhieu;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtMaPhong7;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtsongayo;
    // End of variables declaration//GEN-END:variables
}
