/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hotel.management.system;

import Database.DBConnection;
import Process.ChucNang;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kdt09
 */
public class PanelQLKhachHang extends javax.swing.JPanel {
       String maKH = "";
    /**
     * Creates new form PanelQLKhachHang
     */
    public PanelQLKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCCCD = new javax.swing.JTextField();
        btnXoaKH = new javax.swing.JButton();
        txtNgayDen = new javax.swing.JTextField();
        btnThemKH = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMaPhong = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbLoaiPhong = new javax.swing.JComboBox<>();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_KH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnSuaKH = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        btnXoaKH.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaKH.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/trash.png"))); // NOI18N
        btnXoaKH.setText("Xóa");
        btnXoaKH.setFocusPainted(false);
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });

        txtNgayDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDenActionPerformed(evt);
            }
        });

        btnThemKH.setBackground(new java.awt.Color(50, 204, 255));
        btnThemKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemKH.setForeground(new java.awt.Color(255, 255, 255));
        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/add.png"))); // NOI18N
        btnThemKH.setText("Thêm");
        btnThemKH.setFocusPainted(false);
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Loại Phòng");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Mã Phòng");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Đơn giá");

        cbMaPhong.setEditable(true);
        cbMaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaPhongActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Địa chỉ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("SĐT");

        cbLoaiPhong.setEditable(true);
        cbLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng Đơn", "Phòng Đôi", "Phòng Vip Đơn", "Phòng Vip Đôi", "Phòng Tổng Thống" }));
        cbLoaiPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiPhongItemStateChanged(evt);
            }
        });
        cbLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiPhongActionPerformed(evt);
            }
        });

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        tbl_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "CCCD", "Tên KH", "Giới tính", "Địa Chỉ", "SĐT"
            }
        ));
        tbl_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_KHMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_KH);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Giới tính");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Họ và Tên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("CCCD");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setFocusPainted(false);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        cbGioiTinh.setEditable(true);
        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbGioiTinh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGioiTinhActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Ngày đến");

        btnSuaKH.setBackground(new java.awt.Color(102, 255, 153));
        btnSuaKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaKH.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/edit1.png"))); // NOI18N
        btnSuaKH.setText("Sửa");
        btnSuaKH.setFocusPainted(false);
        btnSuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addGap(45, 45, 45)
                .addComponent(cbMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cbMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11))
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKHActionPerformed
        // TODO add your handling code here:
        String maPhieu = "";

        if (btnSuaKH.getText().equals("Lưu")) {
            DBConnection c = new DBConnection();
            maKH = this.setMaKH();
            maPhieu = this.setMaPhieu();
            String CCCD = txtCCCD.getText();
            String gioiTinh = cbGioiTinh.getSelectedItem().toString();
            String maPhong = cbMaPhong.getSelectedItem().toString();
            String SDT = txtSDT.getText();
            String hoTen = txtHoTen.getText();
            String diaChi = txtDiaChi.getText();
            LocalDate ngayDen = LocalDate.parse(txtNgayDen.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));

            ChucNang.themKH(maKH, CCCD, hoTen, gioiTinh, SDT, diaChi, maPhieu, maPhong, ngayDen);
            DefaultTableModel tbl = (DefaultTableModel) tbl_KH.getModel();
            ChucNang.hienThiKH(tbl);
            btnThemKH.setEnabled(true);
            btnXoaKH.setText("Xóa");
            btnSuaKH.setText("Sửa");
            txtDonGia.setEditable(false);
            txtSDT.setEditable(false);
            txtCCCD.setEditable(false);
            txtHoTen.setEditable(false);
            txtDiaChi.setEditable(false);
            txtNgayDen.setEditable(false);
            cbLoaiPhong.setEditable(false);
            cbGioiTinh.setEditable(false);
            cbMaPhong.setEditable(false);
            txtDonGia.setText("");
            txtSDT.setText("");
            txtCCCD.setText("");
            txtHoTen.setText("");
            txtDiaChi.setText("");
            txtNgayDen.setText("");

        } else {
            btnSuaKH.setEnabled(false);
            btnThemKH.setText("Lưu");
            btnXoaKH.setText("Không Lưu");
            //txtDonGia.setEditable(true);
            txtSDT.setEditable(true);
            cbGioiTinh.setEditable(true);
            //cbLoaiPhong.setEnabled(true);
            //cbMaPhong.setEnabled(true);
            txtCCCD.setEditable(true);
            txtHoTen.setEditable(true);
            txtDiaChi.setEditable(true);
            //txtNgayDen.setEnabled(true);
            //cbLoaiPhong.setEnabled(true);

        }
    }//GEN-LAST:event_btnSuaKHActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        // TODO add your handling code here:
        
        if (btnThemKH.getText() == "Lưu") {

            DBConnection c = new DBConnection();
            String CCCD = txtCCCD.getText();
            String gioiTinh = cbGioiTinh.getSelectedItem().toString();
            String SDT = txtSDT.getText();
            String hoTen = txtHoTen.getText();
            String diaChi = txtDiaChi.getText();

            ChucNang.suaKH(maKH, CCCD, hoTen, gioiTinh, SDT, diaChi);
            DefaultTableModel tbl = (DefaultTableModel) tbl_KH.getModel();
            ChucNang.hienThiKH(tbl);
            btnSuaKH.setEnabled(true);
            btnXoaKH.setText("Xóa");
            btnThemKH.setText("Thêm");
            txtDonGia.setEditable(false);
            txtSDT.setEditable(false);
            txtCCCD.setEditable(false);
            txtHoTen.setEditable(false);
            txtDiaChi.setEditable(false);
            txtNgayDen.setEditable(false);
            cbLoaiPhong.setEditable(false);
            cbGioiTinh.setEditable(false);
            cbMaPhong.setEditable(false);
            txtDonGia.setText("");
            txtCCCD.setText("");
            txtHoTen.setText("");
            txtDiaChi.setText("");
            txtNgayDen.setText("");

        } else {
            btnThemKH.setEnabled(false);
            btnSuaKH.setText("Lưu");
            btnXoaKH.setText("Không Lưu");
            txtSDT.setEditable(false);
            txtCCCD.setEditable(true);
            txtHoTen.setEditable(true);
            txtDiaChi.setEditable(true);
            cbGioiTinh.setEditable(true);
            txtSDT.setEditable(true);
            cbLoaiPhong.setEditable(true);
            cbMaPhong.setEditable(true);
            txtDonGia.setEditable(true);
            txtNgayDen.setEditable(true);
        }
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        // TODO add your handling code here:
        if (btnXoaKH.getText().equalsIgnoreCase("Không Lưu")) {
            btnThemKH.setEnabled(true);
            btnSuaKH.setEnabled(true);
            btnThemKH.setText("Thêm");
            btnXoaKH.setText("Xóa");
            btnSuaKH.setText("Sửa");
            txtDonGia.setEditable(false);
            txtSDT.setEditable(false);
            txtCCCD.setEditable(false);
            txtHoTen.setEditable(false);
            txtDiaChi.setEditable(false);
            txtNgayDen.setEditable(false);
            cbLoaiPhong.setEditable(false);
            cbGioiTinh.setEditable(false);
            cbLoaiPhong.setEditable(false);
            cbMaPhong.setEnabled(false);
            txtDonGia.setText("");
            txtSDT.setText("");
            txtCCCD.setText("");
            txtHoTen.setText("");
            txtDiaChi.setText("");
            txtNgayDen.setText("");

        } else {
            if (txtCCCD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Chọn dữ liệu ở dưới trước!!!!");
            } else {
                int rel = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa", "Xác Nhận Xóa", JOptionPane.YES_NO_OPTION);
                if (rel == JOptionPane.YES_OPTION) {
                    ChucNang.xoaKH(maKH);
                    DefaultTableModel tbl = (DefaultTableModel) tbl_KH.getModel();
                    ChucNang.hienThiKH(tbl);
                }
            }
        }
    }//GEN-LAST:event_btnXoaKHActionPerformed

    private void tbl_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KHMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_KHMouseEntered

    private void tbl_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KHMouseClicked
        // TODO add your handling code here:
        int rowSelect = tbl_KH.getSelectedRow();
        if (rowSelect > -1) {
            maKH = tbl_KH.getValueAt(rowSelect, 0).toString();
            txtCCCD.setText(tbl_KH.getValueAt(rowSelect, 1).toString());
            txtHoTen.setText(tbl_KH.getValueAt(rowSelect, 2).toString());
            cbGioiTinh.setSelectedItem(tbl_KH.getValueAt(rowSelect, 3));
            txtDiaChi.setText(tbl_KH.getValueAt(rowSelect, 4).toString());
            txtSDT.setText(tbl_KH.getValueAt(rowSelect, 5).toString());
        }
    }//GEN-LAST:event_tbl_KHMouseClicked

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void txtNgayDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDenActionPerformed

    private void cbMaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaPhongActionPerformed
        // TODO add your handling code here:
        //txtDonGia.setText(ChucNang.getDonGia(cbMaPhong.getSelectedItem().toString()));
        //cbMaPhong.removeAllItems();
        try {
            ResultSet res = ChucNang.roomChoose(cbMaPhong.getSelectedItem().toString());
            if (res != null) {
                while (res.next()) {
                    String pri = res.getString("price");
                    txtDonGia.setText(pri);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Không còn phòng trống!!!!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbMaPhongActionPerformed

    private void cbLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiPhongActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        cbMaPhong.removeAllItems();
        try {
            ResultSet res = ChucNang.getMaPhong(cbLoaiPhong.getSelectedItem().toString());
            if (res != null) {
                while (res.next()) {
                    String item = res.getString("room_number");
                    cbMaPhong.addItem(item);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Không còn phòng trống!!!!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(QLKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbLoaiPhongActionPerformed

    private void cbLoaiPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiPhongItemStateChanged

    }//GEN-LAST:event_cbLoaiPhongItemStateChanged

    private void cbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGioiTinhActionPerformed
        public String setMaKH() {
        String MaKH;
        if (tbl_KH.getRowCount() - 1 == -1) {
            MaKH = "KH01";
        } else {
            String maCuoi = tbl_KH.getValueAt(tbl_KH.getRowCount() - 1, 0).toString();
            int STT = Integer.parseInt(maCuoi.substring(3)) + 1;
            if (STT >= 10) {
                MaKH = "KH" + STT;
            } else {
                MaKH = "KH0" + STT;
            }
        }
        return MaKH;
    }

    public String setMaPhieu() {
        String MaPhieu;
        if (tbl_KH.getRowCount() - 1 == -1) {
            MaPhieu = "CR01";
        } else {
            String maCuoi = tbl_KH.getValueAt(tbl_KH.getRowCount() - 1, 0).toString();
            int STT = Integer.parseInt(maCuoi.substring(3)) + 1;
            if (STT >= 10) {
                MaPhieu = "CR" + STT;
            } else {
                MaPhieu = "CR0" + STT;
            }
        }
        return MaPhieu;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaKH;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbLoaiPhong;
    private javax.swing.JComboBox<String> cbMaPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_KH;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
