/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hotel.management.system;
import Process.ChucNang;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kdt09
 */
public class PanelQLDichVu extends javax.swing.JPanel {

    /**
     * Creates new form PanelQLDichVu
     */
     int donGia = 0;
    String maLaiXe = "";
    public PanelQLDichVu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Driver = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        btnThue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSoGio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_thoat = new javax.swing.JButton();
        txtLocation = new javax.swing.JTextField();
        lbbackgroud = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Điểm đến:");
        add(jLabel4);
        jLabel4.setBounds(37, 110, 81, 25);

        tbl_Driver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và Tên", "Tuổi", "Giới Tính", "Công Ty", "Hãng Xe", "Có Khách", "Địa Chỉ", "Đơn giá"
            }
        ));
        tbl_Driver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DriverMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Driver);

        add(jScrollPane3);
        jScrollPane3.setBounds(37, 180, 1103, 273);

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setPreferredSize(new java.awt.Dimension(93, 33));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem);
        btnTimKiem.setBounds(487, 108, 121, 33);

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTongTien.setToolTipText("");
        add(txtTongTien);
        txtTongTien.setBounds(191, 547, 249, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Số CCCD");
        add(jLabel1);
        jLabel1.setBounds(37, 459, 72, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tổng tiền");
        add(jLabel5);
        jLabel5.setBounds(37, 550, 75, 25);

        txtCCCD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCCCD.setToolTipText("");
        add(txtCCCD);
        txtCCCD.setBounds(191, 459, 249, 32);

        btnThue.setBackground(new java.awt.Color(51, 255, 0));
        btnThue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThue.setText("Thuê");
        btnThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThueActionPerformed(evt);
            }
        });
        add(btnThue);
        btnThue.setBounds(532, 483, 121, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Số giờ thuê");
        add(jLabel2);
        jLabel2.setBounds(37, 506, 92, 25);

        txtSoGio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoGio.setToolTipText("");
        add(txtSoGio);
        txtSoGio.setBounds(191, 503, 249, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("QUẢN LÝ DỊCH VỤ");
        add(jLabel3);
        jLabel3.setBounds(6, 20, 1190, 48);

        btn_thoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        add(btn_thoat);
        btn_thoat.setBounds(532, 527, 121, 32);

        txtLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLocation.setToolTipText("");
        txtLocation.setPreferredSize(new java.awt.Dimension(64, 33));
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        add(txtLocation);
        txtLocation.setBounds(138, 108, 302, 33);
        add(lbbackgroud);
        lbbackgroud.setBounds(0, 74, 0, 0);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_DriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DriverMouseClicked
        // TODO add your handling code here:
        int rowSelect = tbl_Driver.getSelectedRow();
        if (rowSelect > -1) {
            maLaiXe = (tbl_Driver.getValueAt(rowSelect, 0).toString());
            donGia =  Integer.parseInt((tbl_Driver.getValueAt(rowSelect, 8).toString()));

        }
    }//GEN-LAST:event_tbl_DriverMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) tbl_Driver.getModel();
        ChucNang.hienThiDriverbyLocation(tbl, txtLocation.getText());
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThueActionPerformed
        // TODO add your handling code here:
        int tongTien = donGia * Integer.parseInt(txtSoGio.getText());
        String maPTX;
        String res = ChucNang.getMaPhieuXe();
        if(res == ""){
            maPTX = "CR01";
        }
        else{
            int stt = Integer.parseInt(res.substring(3)) + 1;
            if(stt > 9){
                maPTX = "CR" + stt;
            }
            else{
                maPTX = "CR0" + stt;
            }
        }
        String maKH = ChucNang.getMaKH(txtCCCD.getText());
        ChucNang.themPhieuThueXe(maPTX, maKH, maLaiXe, txtSoGio.getText(), tongTien);
        txtTongTien.setText(String.valueOf(tongTien));
    }//GEN-LAST:event_btnThueActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThue;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbbackgroud;
    private javax.swing.JTable tbl_Driver;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtSoGio;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
