/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import Database.DBConnection;
import Process.ChucNang;
import com.mysql.cj.protocol.Message;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kdt09
 */
public class QLLaiXe extends javax.swing.JFrame {

    String ma;

    /**
     * Creates new form AddDrivers1
     */
    public QLLaiXe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        comboBox_1 = new javax.swing.JComboBox<>();
        btnThemDriver = new javax.swing.JButton();
        lb_anh = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Driver = new javax.swing.JTable();
        btnSuaDriver = new javax.swing.JButton();
        btnXoaDriver = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        t6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Lái Xe");
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ LÁI XE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Họ và  Tên");

        t1.setEnabled(false);

        t2.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Tuổi");

        t3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Công ty");

        t4.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Hãng xe");

        t5.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Đã Có Khách");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Địa Chỉ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Giới tính");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        comboBox.setEnabled(false);
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        comboBox_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có", "Không" }));
        comboBox_1.setEnabled(false);
        comboBox_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_1ActionPerformed(evt);
            }
        });

        btnThemDriver.setBackground(new java.awt.Color(51, 204, 255));
        btnThemDriver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemDriver.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/add.png"))); // NOI18N
        btnThemDriver.setText("Thêm");
        btnThemDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDriverActionPerformed(evt);
            }
        });

        lb_anh.setFont(new java.awt.Font("Segoe UI Emoji", 0, 3)); // NOI18N
        lb_anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/unname.jpg"))); // NOI18N
        lb_anh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_anh.setIconTextGap(1);
        lb_anh.setInheritsPopupMenu(false);
        lb_anh.setMaximumSize(new java.awt.Dimension(500, 300));
        lb_anh.setMinimumSize(new java.awt.Dimension(500, 300));
        lb_anh.setPreferredSize(new java.awt.Dimension(500, 300));

        tbl_Driver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và Tên", "Tuổi", "Giới Tính", "Công Ty", "Hãng Xe", "Có Khách", "Địa Chỉ", "Đơn giá"
            }
        ));
        tbl_Driver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DriverMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Driver);
        if (tbl_Driver.getColumnModel().getColumnCount() > 0) {
            tbl_Driver.getColumnModel().getColumn(0).setMinWidth(20);
            tbl_Driver.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        btnSuaDriver.setBackground(new java.awt.Color(102, 255, 153));
        btnSuaDriver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaDriver.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/edit1.png"))); // NOI18N
        btnSuaDriver.setText("Sửa");
        btnSuaDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDriverActionPerformed(evt);
            }
        });

        btnXoaDriver.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaDriver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaDriver.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/trash.png"))); // NOI18N
        btnXoaDriver.setText("Xóa");
        btnXoaDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDriverActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        t6.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Đơn giá");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addGap(30, 30, 30))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(t1)
                            .addComponent(t2)
                            .addComponent(comboBox, 0, 230, Short.MAX_VALUE)
                            .addComponent(t3)
                            .addComponent(t4)
                            .addComponent(comboBox_1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboBox_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemDriver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoaDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSuaDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        lb_anh.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed

    private void btnThemDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDriverActionPerformed
        // TODO add your handling code here:
        if (btnThemDriver.getText() == "Lưu") {
            DBConnection c = new DBConnection();
            String name = t1.getText();
            String age = t2.getText();
            String gender = (String) comboBox.getSelectedItem();
            String company = t3.getText();
            String brand = t4.getText();
            String available = (String) comboBox_1.getSelectedItem();
            String location = t5.getText();
            String donGia = t6.getText();
            ChucNang.suaDriver(name, age, gender, company, brand, available, location, ma , donGia);
            DefaultTableModel tbl = (DefaultTableModel) tbl_Driver.getModel();
            ChucNang.hienThiDriver(tbl);
            btnSuaDriver.setEnabled(true);
            btnThemDriver.setText("Thêm");
            btnXoaDriver.setText("Xóa");
            t1.setEnabled(false);
            t2.setEnabled(false);
            t3.setEnabled(false);
            t4.setEnabled(false);
            t5.setEnabled(false);
            t6.setEnabled(false);
            comboBox.setEnabled(false);
            comboBox_1.setEnabled(false);
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            t6.setText("");
        } else {
            btnThemDriver.setEnabled(false);
            btnSuaDriver.setText("Lưu");
            btnXoaDriver.setText("Không Lưu");
            t1.setEnabled(true);
            t2.setEnabled(true);
            t3.setEnabled(true);
            t4.setEnabled(true);
            t5.setEnabled(true);
            t6.setEnabled(true);
            comboBox.setEnabled(true);
            comboBox_1.setEnabled(true);
        }


    }//GEN-LAST:event_btnThemDriverActionPerformed

    private void comboBox_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboBox_1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) tbl_Driver.getModel();
        ChucNang.hienThiDriver(tbl);
        ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("hotel/management/system/icons/eleven.jpg"));
        Image i3 = i1.getImage().getScaledInstance(500, 400, Image.SCALE_DEFAULT);
        ImageIcon i2 = new ImageIcon(i3);
        lb_anh.setIcon(i2);


    }//GEN-LAST:event_formWindowOpened

    private void btnSuaDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDriverActionPerformed
        // TODO add your handling code here:
        if (t1.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Chọn dữ liệu ở dưới trước!!!!");
        } else {
            if (btnSuaDriver.getText() == "Lưu") {
                DBConnection c = new DBConnection();
                String name = t1.getText();
                String age = t2.getText();
                String gender = (String) comboBox.getSelectedItem();
                String company = t3.getText();
                String brand = t4.getText();
                String available = (String) comboBox_1.getSelectedItem();
                String location = t5.getText();
                String donGia = t6.getText();
                ma = this.setMaDri();
                ChucNang.themDriver(ma, name, age, gender, company, brand, available, location, donGia);
                DefaultTableModel tbl = (DefaultTableModel) tbl_Driver.getModel();
                ChucNang.hienThiDriver(tbl);
                btnThemDriver.setEnabled(true);
                btnSuaDriver.setText("Sửa");
                btnXoaDriver.setText("Xóa");
                t1.setEnabled(false);
                t2.setEnabled(false);
                t3.setEnabled(false);
                t4.setEnabled(false);
                t5.setEnabled(false);
                t6.setEnabled(false);
                comboBox.setEnabled(false);
                comboBox_1.setEnabled(false);

            } else {
                btnSuaDriver.setEnabled(false);
                btnThemDriver.setText("Lưu");
                btnXoaDriver.setText("Không Lưu");
                t1.setEnabled(true);
                t2.setEnabled(true);
                t3.setEnabled(true);
                t4.setEnabled(true);
                t5.setEnabled(true);
                t6.setEnabled(true);
                comboBox.setEnabled(true);
                comboBox_1.setEnabled(true);
            }
        }


    }//GEN-LAST:event_btnSuaDriverActionPerformed

    private void btnXoaDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDriverActionPerformed
        // TODO add your handling code here:
        if (btnXoaDriver.getText().equalsIgnoreCase("Không Lưu")) {
            btnSuaDriver.setEnabled(true);
            btnThemDriver.setEnabled(true);
            btnThemDriver.setText("Thêm");
            btnXoaDriver.setText("Xóa");
            btnSuaDriver.setText("Sửa");
            t1.setEnabled(false);
            t2.setEnabled(false);
            t3.setEnabled(false);
            t4.setEnabled(false);
            t5.setEnabled(false);
            t6.setEnabled(false);
            comboBox.setEnabled(false);
            comboBox_1.setEnabled(false);
        } else {
            if (t1.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Chọn dữ liệu ở dưới trước!!!!");
            } else {
                int rel = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa", "Xác Nhận Xóa", JOptionPane.YES_NO_OPTION);
                if (rel == JOptionPane.YES_OPTION) {
                    ChucNang.xoaDriver(ma);
                    DefaultTableModel tbl = (DefaultTableModel) tbl_Driver.getModel();
                    ChucNang.hienThiDriver(tbl);
                }
            }
        }
    }//GEN-LAST:event_btnXoaDriverActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tbl_DriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DriverMouseClicked
        // TODO add your handling code here:
        int rowSelect = tbl_Driver.getSelectedRow();
        if (rowSelect > -1) {
            ma = (tbl_Driver.getValueAt(rowSelect, 0).toString());
            t1.setText(tbl_Driver.getValueAt(rowSelect, 1).toString());
            t2.setText(tbl_Driver.getValueAt(rowSelect, 2).toString());
            comboBox.setSelectedItem(tbl_Driver.getValueAt(rowSelect, 3));
            t3.setText(tbl_Driver.getValueAt(rowSelect, 4).toString());
            t4.setText(tbl_Driver.getValueAt(rowSelect, 5).toString());
            comboBox_1.setSelectedItem(tbl_Driver.getValueAt(rowSelect, 6));
            t5.setText(tbl_Driver.getValueAt(rowSelect, 7).toString());
            t6.setText(tbl_Driver.getValueAt(rowSelect, 8).toString());
        }
    }//GEN-LAST:event_tbl_DriverMouseClicked

    public String setMaDri() {
        String MaDri;
        if (tbl_Driver.getRowCount() - 1 == -1) {
            MaDri = "Dri01";
        } else {
            String maCuoi = tbl_Driver.getValueAt(tbl_Driver.getRowCount() - 1, 0).toString();
            int STT = Integer.parseInt(maCuoi.substring(3)) + 1;
            if (STT >= 10) {
                MaDri = "Dri" + STT;
            } else {
                MaDri = "Dri0" + STT;
            }
        }
        return MaDri;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLaiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaDriver;
    private javax.swing.JButton btnThemDriver;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaDriver;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JComboBox<String> comboBox_1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTable tbl_Driver;
    // End of variables declaration//GEN-END:variables
}
