/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import Database.DBConnection;
import Process.ChucNang;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kdt09
 */
public class QLPhong extends javax.swing.JFrame {

    /**
     * Creates new form QLPhong
     */
    public QLPhong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXoaPhong = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbTinhTrang = new javax.swing.JComboBox<>();
        cbLoaiPhong = new javax.swing.JComboBox<>();
        btnThemPhong = new javax.swing.JButton();
        lb_anh = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Phong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDVTinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSuaPhong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Phòng");
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnXoaPhong.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/trash.png"))); // NOI18N
        btnXoaPhong.setText("Xóa");
        btnXoaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhongActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Loại phòng");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Tình trạng");

        cbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "trống", "có khách" }));
        cbTinhTrang.setEnabled(false);
        cbTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTinhTrangActionPerformed(evt);
            }
        });

        cbLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "phòng đơn", "phòng đôi", "phòng vip đơn", "phòng vip đôi", "phòng tổng thống" }));
        cbLoaiPhong.setEnabled(false);
        cbLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiPhongActionPerformed(evt);
            }
        });

        btnThemPhong.setBackground(new java.awt.Color(51, 204, 255));
        btnThemPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnThemPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/add.png"))); // NOI18N
        btnThemPhong.setText("Thêm");
        btnThemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhongActionPerformed(evt);
            }
        });

        lb_anh.setFont(new java.awt.Font("Segoe UI Emoji", 0, 3)); // NOI18N
        lb_anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/pp.jpg"))); // NOI18N
        lb_anh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_anh.setIconTextGap(1);
        lb_anh.setInheritsPopupMenu(false);
        lb_anh.setMaximumSize(new java.awt.Dimension(0, 0));
        lb_anh.setMinimumSize(new java.awt.Dimension(0, 0));
        lb_anh.setPreferredSize(new java.awt.Dimension(500, 300));

        tbl_Phong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Loại Phòng", "Tình trạng", "Đơn giá", "Đơn vị tính"
            }
        ));
        tbl_Phong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PhongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Phong);
        if (tbl_Phong.getColumnModel().getColumnCount() > 0) {
            tbl_Phong.getColumnModel().getColumn(0).setMinWidth(30);
            tbl_Phong.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHÒNG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Mã Phòng");

        txtMaPhong.setEnabled(false);

        txtDonGia.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Đơn Giá");

        txtDVTinh.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Đơn vị tính");

        btnSuaPhong.setBackground(new java.awt.Color(102, 255, 153));
        btnSuaPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/icons/edit1.png"))); // NOI18N
        btnSuaPhong.setText("Sửa");
        btnSuaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTinhTrang, 0, 252, Short.MAX_VALUE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(txtDVTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(cbLoaiPhong, 0, 252, Short.MAX_VALUE)
                            .addComponent(txtMaPhong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDVTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_anh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhongActionPerformed
        // TODO add your handling code here:
        if (btnXoaPhong.getText().equalsIgnoreCase("Không Lưu")) {
            btnSuaPhong.setEnabled(true);
            btnThemPhong.setEnabled(true);
            btnThemPhong.setText("Thêm");
            btnXoaPhong.setText("Xóa");
            btnSuaPhong.setText("Sửa");
            txtDVTinh.setEnabled(false);
            txtDonGia.setEnabled(false);
            txtMaPhong.setEnabled(false);
            cbLoaiPhong.setEnabled(false);
            cbTinhTrang.setEnabled(false);

        } else {
            if (txtDVTinh.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Chọn dữ liệu ở dưới trước!!!!");
            } else {
                int rel = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa", "Xác Nhận Xóa", JOptionPane.YES_NO_OPTION);
                if (rel == JOptionPane.YES_OPTION) {
                    ChucNang.xoaPhong(txtMaPhong.getText());
                    DefaultTableModel tbl = (DefaultTableModel) tbl_Phong.getModel();
                    ChucNang.hienThiPhong(tbl);
                }
            }
        }
    }//GEN-LAST:event_btnXoaPhongActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTinhTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTinhTrangActionPerformed

    private void cbLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoaiPhongActionPerformed

    private void btnThemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhongActionPerformed
        // TODO add your handling code here:
        if (btnThemPhong.getText() == "Lưu") {
            DBConnection c = new DBConnection();
            String maPhong = txtMaPhong.getText();
            String loaiPhong = cbLoaiPhong.getSelectedItem().toString();
            String tinhTrang = (String) cbTinhTrang.getSelectedItem();
            String donGia = txtDonGia.getText();
            String dvTinh = txtDVTinh.getText();

            ChucNang.suaPhong(maPhong, loaiPhong, tinhTrang, donGia, dvTinh);
            DefaultTableModel tbl = (DefaultTableModel) tbl_Phong.getModel();
            ChucNang.hienThiPhong(tbl);
            btnSuaPhong.setEnabled(true);
            btnXoaPhong.setText("Xóa");
            btnThemPhong.setText("Thêm");
            txtDVTinh.setEnabled(false);
            txtDonGia.setEnabled(false);
            txtMaPhong.setEnabled(false);
            cbLoaiPhong.setEnabled(false);
            cbTinhTrang.setEnabled(false);
            txtDVTinh.setText("");
            txtDonGia.setText("");
            txtMaPhong.setText("");

        } else {
            btnThemPhong.setEnabled(false);
            btnSuaPhong.setText("Lưu");
            btnXoaPhong.setText("Không Lưu");
            txtDVTinh.setEnabled(true);
            txtDonGia.setEnabled(true);
            txtMaPhong.setEnabled(true);
            cbLoaiPhong.setEnabled(true);
            cbTinhTrang.setEnabled(true);

        }


    }//GEN-LAST:event_btnThemPhongActionPerformed

    private void btnSuaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPhongActionPerformed
        // TODO add your handling code here:
        if (txtDVTinh.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Chọn dữ liệu ở dưới trước!!!!");
        } else {
            if (btnSuaPhong.getText() == "Lưu") {
                DBConnection c = new DBConnection();
                String maPhong = txtMaPhong.getText();
                String loaiPhong = cbLoaiPhong.getSelectedItem().toString();
                String tinhTrang = cbTinhTrang.getSelectedItem().toString();
                String donGia = txtDonGia.getText();
                String dvTinh = txtDVTinh.getText();

                ChucNang.themPhong(maPhong, loaiPhong, tinhTrang, donGia, dvTinh);
                DefaultTableModel tbl = (DefaultTableModel) tbl_Phong.getModel();
                ChucNang.hienThiPhong(tbl);
                btnThemPhong.setEnabled(true);
                btnXoaPhong.setText("Xóa");
                btnSuaPhong.setText("Sửa");
                txtDVTinh.setEnabled(false);
                txtDonGia.setEnabled(false);
                txtMaPhong.setEnabled(false);
                cbLoaiPhong.setEnabled(false);
                cbTinhTrang.setEnabled(false);
                txtDVTinh.setText("");
                txtDonGia.setText("");
                txtMaPhong.setText("");

            } else {
                btnSuaPhong.setEnabled(false);
                btnThemPhong.setText("Lưu");
                btnXoaPhong.setText("Không Lưu");
                txtDVTinh.setEnabled(true);
                txtDonGia.setEnabled(true);
                txtMaPhong.setEnabled(true);
                cbLoaiPhong.setEnabled(true);
                cbTinhTrang.setEnabled(true);

            }
        }

    }//GEN-LAST:event_btnSuaPhongActionPerformed


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) tbl_Phong.getModel();
        ChucNang.hienThiPhong(tbl);
        ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("hotel/management/system/icons/eleven.jpg"));
        Image i3 = i1.getImage().getScaledInstance(500, 400, Image.SCALE_DEFAULT);
        ImageIcon i2 = new ImageIcon(i3);
        lb_anh.setIcon(i2);
    }//GEN-LAST:event_formWindowOpened

    private void tbl_PhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_PhongMouseClicked
        // TODO add your handling code here:
        int rowSelect = tbl_Phong.getSelectedRow();
        if (rowSelect > -1) {
            txtMaPhong.setText(tbl_Phong.getValueAt(rowSelect, 0).toString());
            txtDonGia.setText(tbl_Phong.getValueAt(rowSelect, 3).toString());
            txtDVTinh.setText(tbl_Phong.getValueAt(rowSelect, 4).toString());
            cbLoaiPhong.setSelectedItem(tbl_Phong.getValueAt(rowSelect, 1));

            cbTinhTrang.setSelectedItem(tbl_Phong.getValueAt(rowSelect, 2));

        }
    }//GEN-LAST:event_tbl_PhongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaPhong;
    private javax.swing.JButton btnThemPhong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaPhong;
    private javax.swing.JComboBox<String> cbLoaiPhong;
    private javax.swing.JComboBox<String> cbTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JTable tbl_Phong;
    private javax.swing.JTextField txtDVTinh;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaPhong;
    // End of variables declaration//GEN-END:variables
}
